### ISSUE TITLE
Spring Boot 3 Compatiblility

### ISSUE THREAD

**Issue by tadlakha9** [ePages-de/restdocs-api-spec#224] opened 2023-01-23 10:11 UTC
Needs support to migrate epages to spring boot3 so that it would be compatible with other projects which are migrating to spring boot3 but currently facing issue as epages is on spring boot 2.1.9.RELEASE

**Comment by ozscheyge** [comment] 2023-01-23 12:12
Closing as duplicate of https://github.com/ePages-de/restdocs-api-spec/issues/211

**Closed by ozscheyge** 2023-01-23 12:12 UTC
