### ISSUE TITLE
FieldDescriptor optional() is not working

### ISSUE THREAD

**Issue by traeper** [ePages-de/restdocs-api-spec#172] opened 2021-04-26 12:53 UTC
Hello. 
I'm gratefully use restdocs-api-spec in my company.

Overall, it seems that the API specification is well generated. However, even if the FieldDescriptor entering the requestFields/responseFields is written to perform optional(), the generated yml file does not display the optional value.

Could you please tell me how to display the nullable value in requestFields/responseFields

Thanks in advance.

**Comment by traeper** [comment] 2021-04-26 12:56
I found ConstrainedFields that may fix my issue.
Thanks. :D

**Comment by ozscheyge** [comment] 2021-04-26 12:59
Hey!

`optional()` should work even for regular FieldDescriptors. Which target format are you generating?

**Comment by traeper** [comment] 2021-04-26 14:09
I want to generate 'nullable' property.

API RequestBody data object has nullable value. (metadata)



* mockMvc test code
```kotlin
mockMvc.perform(
            post("/api/v1/test")
                .param("transaction_id", transactionId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(json)
        )
            .andExpect(status().isOk)
            .andExpect(content().contentType(MediaType.APPLICATION_JSON))
            .andDo(
                MockMvcRestDocumentationWrapper.document(
                    "test/{methodName}",
                    requestParameters(requestParameterDescriptors()),
                    requestFields(requestFieldDescriptors()),
                    responseFields(responseFieldDescriptors())
                )
            )
```

* private descriptors codes
```kotlin
    private fun requestParameterDescriptors(): List<ParameterDescriptor> = listOf(
        parameterWithName("transaction_id").description("transaction id")
    )

    private fun requestFieldDescriptors(): List<FieldDescriptor> =
        listOf(
            fieldWithPath("number1").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("number2").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("type").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("content").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("metadata").type(JsonFieldType.STRING).description("desc").optional(),
        )

    private fun responseFieldDescriptors(): List<FieldDescriptor> = listOf(
        fieldWithPath("transaction_id").type(JsonFieldType.STRING)
            .description("transaction id")
    )
```


the result of yml file is below. 
metadata is not optional (I need to generate nullable or required)

```yaml
    api-v1-test-hmac793873085:
      type: object
      properties:
        metadata:
          type: string
          description: desc
        number2:
          type: string
          description: desc
        number1:
          type: string
          description: desc
        type:
          type: string
          description: desc
        content:
          type: string
          description: desc
```

**Comment by traeper** [comment] 2021-04-26 14:29
When add optional() to `parameterWithName("transaction_id").description("transaction id")` in requestParameterDescriptors() method, result of yml file added **required: false** correctly

**Comment by ozscheyge** [comment] 2021-04-28 19:07
I could reproduce the issue for both OpenAPI 2 and OpenAPI 3 generators. The info is correctly gathered in `resource.json` snippet from the descriptors, but not utilized by the OpenAPI generators. So far, we seem to only value the optional for ParameterDescriptors.

How it should look like (`required` property in the schema object with an array of required fields, same level as `properties`):
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#schema-object-examples
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object-examples
https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.15

**Comment by ozscheyge** [comment] 2021-04-28 19:11
Seems to be a duplicate of https://github.com/ePages-de/restdocs-api-spec/issues/90

**Comment by ozscheyge** [comment] 2021-08-10 19:24
Should be fixed with https://github.com/ePages-de/restdocs-api-spec/pull/183

**Closed by ozscheyge** 2021-08-10 19:24 UTC
Labels: bug, duplicate

**Comment by GoodGoodJM** [comment] 2021-08-14 03:18
When can we use the version which this issue has been resolved? Is there a scheduled date?

**Comment by ooz** [comment] 2021-08-16 09:11
> When can we use the version which this issue has been resolved? Is there a scheduled date?

Hey @GoodGoodJM ,
I hoped to resolve another issue with the same release, but it isn't moving, so I'll release a new version now, ETA+1h.

Sorry for the inconvenience!
