### ISSUE TITLE
Request and response samples are quoted in Redoc

### ISSUE THREAD

**Issue by arhohuttunen** [ePages-de/restdocs-api-spec#111] opened 2019-08-01 11:01 UTC
The culprit of this is explained here: https://github.com/Redocly/redoc/issues/205

To get the collapse/expand functionality there, the examples should be stored in YAML format.

**Comment by ozscheyge** [comment] 2020-02-28 10:44
Afaics, we are rendering correct OpenAPI 2, but redoc would like to have the yaml example string in a certain format/syntax?

**Comment by arhohuttunen** [comment] 2020-04-17 17:29
I seem to have forgotten to answer to this. The problem is not that the example has wrong string format, but that it _is a string_, since using `|-` denotes a string.

```yaml
examples:
  application/json: |-
    {
      "foo": "bar"
    }
```

This cannot be rendered as an object, since it’s not. It is a string representation of the object we need.

The correct way to represent the example would be to use an actual object:

```yaml
examples:
  application/json:
    {
      ”foo”: ”bar”
    }
```

Reference: https://swagger.io/docs/specification/2-0/adding-examples/

The same happens with JSON output as well, because the example is wrapped in quotes. What we ended up doing to work around this was to parse the output ourselves to get rid of the extra characters in examples.

**Comment by kiftio** [comment] 2020-06-30 10:17
Fyi - after upgrading to spring boot 2.3.x, and transitively to jackson 2.11.0, this is now a bit tricker to work around.

Where we used to get this output: 
```
  |-
  {
      "a":"b",
      "c":"d"
  }
```

We now get:
```
"{\n    \"a\":\"b\",\n    \"c\":\"d\"\n}"
```

So it's no longer just a case of removing `|-` to get redoc to display unquoted request / response samples.

I think it's potentially due to this change - https://github.com/FasterXML/jackson-dataformats-text/commit/c41a621c5aff69ba663d2491e6fbc861e338e5b5#diff-6eedc03a68a69933c763e674f2d7c42f

**Comment by thugcee** [comment] 2020-11-30 20:19
> So it's no longer just a case of removing `|-` to get redoc to display unquoted request / response samples.

Try this workaround: https://github.com/ePages-de/restdocs-api-spec/issues/109#issuecomment-736012775

**Comment by ozscheyge** [comment] 2021-01-04 20:21
Based on kiftio's findings and https://yaml.org/spec/1.2/spec.html#id2788859, I'd say: quoting of the example is working as intended by YAML spec and I'd close this. 

thugcee provided a nice workaround for redoc users.

**Closed by ozscheyge** 2021-01-04 20:21 UTC
Labels: bug
